export { generateImagesPath } from './utils/image-src/generate-images-path';
export { preloadImages } from './utils/load-images/preload-images';
export { contain } from './utils/responsive/contain';
export { getCurrentOriginalImage } from './utils/magnify/get-current-original-image';
export { magnify } from './utils/magnify/magnify';
export { getSpeedFactor } from './utils/auto-play/getSpeedFactor';
export { isCompletedOneCycle } from './utils/auto-play/is-completed-one-cycle';
export { getContainerResponsiveWidth } from './utils/responsive/get-container-responsive-width';
export { getContainerResponsiveHeight } from './utils/responsive/get-container-responsive-height';
export { getMovingDirection } from './utils/spin-y/get-moving-direction';
export { initControls } from './utils/controls/initControls';
export { addClass } from './utils/common/add-class';
export { removeClass } from './utils/common/remove-class';
export { getItemSkipped } from './utils/controls/get-item-skipped';
export * from './utils/container-elements';
export { loop } from './utils/auto-play/loop';
